# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-07 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MMLCmdInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmdname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ResponsibilityField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(max_length=50)),
                ('introduce', models.URLField()),
                ('plname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Solution1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solutionname', models.CharField(max_length=200)),
                ('is_question', models.BooleanField(default=False)),
                ('url', models.URLField()),
                ('next_solution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base_assistant.Solution1', verbose_name='子解决方法')),
            ],
        ),
        migrations.CreateModel(
            name='VersionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=20)),
                ('platform_ver', models.CharField(max_length=20)),
                ('product_ver', models.CharField(max_length=20)),
                ('verinfo', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='mmlcmdinfo',
            name='responsefield',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_assistant.ResponsibilityField'),
        ),
        migrations.AddField(
            model_name='mmlcmdinfo',
            name='solutions',
            field=models.ManyToManyField(to='base_assistant.Solution1'),
        ),
    ]
