# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-06 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MMLCmdInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmdname', models.CharField(max_length=30)),
                ('cmd_func', models.CharField(max_length=300)),
                ('cmd_sample', models.CharField(max_length=50)),
                ('cmd_attention', models.CharField(max_length=500)),
                ('cmd_mark', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='OuterLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_title', models.CharField(max_length=128)),
                ('introduce', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ResponsibilityField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(max_length=50, unique=True)),
                ('introduce', models.URLField()),
                ('plname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solutionname', models.CharField(max_length=200)),
                ('is_question', models.BooleanField(default=False)),
                ('url', models.URLField()),
                ('next_solution', models.ManyToManyField(to='base_assistant.Solution', verbose_name='子解决方法')),
            ],
        ),
        migrations.CreateModel(
            name='VersionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=20)),
                ('platform_ver', models.CharField(max_length=20)),
                ('product_ver', models.CharField(max_length=20)),
                ('verinfo', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='mmlcmdinfo',
            name='out_links',
            field=models.ManyToManyField(to='base_assistant.OuterLink'),
        ),
        migrations.AddField(
            model_name='mmlcmdinfo',
            name='responsefield',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_assistant.ResponsibilityField'),
        ),
        migrations.AddField(
            model_name='mmlcmdinfo',
            name='solutions',
            field=models.ManyToManyField(to='base_assistant.Solution'),
        ),
        migrations.AddField(
            model_name='hashtag',
            name='solution',
            field=models.ManyToManyField(to='base_assistant.Solution'),
        ),
    ]
