# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-30 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_assistant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=30)),
                ('introduce', models.CharField(max_length=50)),
                ('path', models.CharField(max_length=100)),
                ('responsefield', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_assistant.ResponsibilityField')),
            ],
        ),
        migrations.CreateModel(
            name='ResoureInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=200)),
                ('cmd_mark', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='mmlcmdinfo',
            name='out_links',
            field=models.ManyToManyField(null=True, to='base_assistant.OuterLink'),
        ),
        migrations.AlterField(
            model_name='mmlcmdinfo',
            name='solutions',
            field=models.ManyToManyField(null=True, to='base_assistant.Solution'),
        ),
        migrations.CreateModel(
            name='ResourceInfoModule',
            fields=[
                ('resoureinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base_assistant.ResoureInfo')),
                ('introduct', models.CharField(max_length=500)),
                ('out_link', models.URLField()),
            ],
            bases=('base_assistant.resoureinfo',),
        ),
        migrations.CreateModel(
            name='ResourceInfoStr',
            fields=[
                ('resoureinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base_assistant.ResoureInfo')),
                ('value', models.CharField(max_length=50)),
            ],
            bases=('base_assistant.resoureinfo',),
        ),
        migrations.CreateModel(
            name='ResoureInfoInt',
            fields=[
                ('resoureinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base_assistant.ResoureInfo')),
                ('value', models.IntegerField()),
            ],
            bases=('base_assistant.resoureinfo',),
        ),
        migrations.AddField(
            model_name='resoureinfo',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_assistant.FileInfo'),
        ),
        migrations.AddField(
            model_name='resoureinfo',
            name='out_links',
            field=models.ManyToManyField(null=True, to='base_assistant.OuterLink'),
        ),
        migrations.AddField(
            model_name='resoureinfo',
            name='responsefield',
            field=models.ManyToManyField(blank=True, null=True, to='base_assistant.ResponsibilityField'),
        ),
        migrations.AddField(
            model_name='resoureinfo',
            name='solutions',
            field=models.ManyToManyField(null=True, to='base_assistant.Solution'),
        ),
        migrations.CreateModel(
            name='ResourceInfoRud',
            fields=[
                ('resoureinfoint_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base_assistant.ResoureInfoInt')),
                ('domain', models.CharField(max_length=30)),
            ],
            bases=('base_assistant.resoureinfoint',),
        ),
    ]
