# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-03 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_assistant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mmlcmdinfo',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='base_assistant.HashTag'),
        ),
    ]
