# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 14:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_assistant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MMLCmdInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmdname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ResponsibilityField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(max_length=50)),
                ('introduce', models.URLField()),
                ('plname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solutionname', models.CharField(max_length=100)),
                ('url', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='mmlcmdinfo',
            name='responsefield',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_assistant.ResponsibilityField'),
        ),
        migrations.AddField(
            model_name='mmlcmdinfo',
            name='solutions',
            field=models.ManyToManyField(to='base_assistant.Solution'),
        ),
    ]
