# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-07 16:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_assistant', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Solution1',
            new_name='Solution',
        ),
    ]
