# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-03 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_assistant', '0002_mmlcmdinfo_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='EVTCmdInfo',
            fields=[
                ('searchobj_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base_assistant.SearchObj')),
                ('cmdname', models.CharField(max_length=30)),
                ('cmd_func', models.CharField(max_length=300)),
                ('cmd_attention', models.CharField(max_length=500)),
                ('cmd_mark', models.TextField()),
                ('responsefield', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_assistant.ResponsibilityField')),
                ('tags', models.ManyToManyField(blank=True, null=True, to='base_assistant.HashTag')),
            ],
            bases=('base_assistant.searchobj',),
        ),
    ]
