# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-25 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_assistant', '0002_auto_20171230_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='resoureinfoint',
            name='hexval',
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mmlcmdinfo',
            name='out_links',
            field=models.ManyToManyField(blank=True, null=True, to='base_assistant.OuterLink'),
        ),
        migrations.AlterField(
            model_name='mmlcmdinfo',
            name='solutions',
            field=models.ManyToManyField(blank=True, null=True, to='base_assistant.Solution'),
        ),
        migrations.AlterField(
            model_name='resoureinfo',
            name='out_links',
            field=models.ManyToManyField(blank=True, null=True, to='base_assistant.OuterLink'),
        ),
        migrations.AlterField(
            model_name='resoureinfo',
            name='solutions',
            field=models.ManyToManyField(blank=True, null=True, to='base_assistant.Solution'),
        ),
    ]
