# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-07 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_assistant', '0002_auto_20170908_0023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='next_solution',
        ),
        migrations.AddField(
            model_name='solution',
            name='next_solution',
            field=models.ManyToManyField(blank=True, null=True, related_name='_solution_next_solution_+', to='base_assistant.Solution', verbose_name='子解决方法'),
        ),
    ]
