# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-25 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_assistant', '0003_auto_20180425_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileinfo',
            name='out_links',
            field=models.ManyToManyField(blank=True, null=True, to='base_assistant.OuterLink'),
        ),
        migrations.AddField(
            model_name='fileinfo',
            name='solutions',
            field=models.ManyToManyField(blank=True, null=True, to='base_assistant.Solution'),
        ),
    ]
