# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-29 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_assistant', '0003_evtcmdinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikiinfo',
            name='contetn',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
