# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-08 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_assistant', '0003_auto_20170908_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='next_solution',
            field=models.ManyToManyField(related_name='_solution_next_solution_+', to='base_assistant.Solution', verbose_name='子解决方法'),
        ),
    ]
