# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-09 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_assistant', '0005_auto_20170909_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('solution', models.ManyToManyField(to='base_assistant.Solution')),
            ],
        ),
    ]
