# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-10 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_assistant', '0006_hashtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mmlcmdinfo',
            name='solutions',
            field=models.ManyToManyField(blank=True, null=True, to='base_assistant.Solution'),
        ),
        migrations.AlterField(
            model_name='responsibilityfield',
            name='groupname',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
